---
- hosts: all
  remote_user: ec2-user
  gather_facts: False

  tasks:

  - name: apache restart
    service: name=httpd state=restarted

  - name: check if httpd has port 443 open
    shell: ss -tp state listening sport = :443 | grep httpd
